name: ci

on:
  pull_request:
    branches: [develop]
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Cache node_modules
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.npm
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format:check # remember to check and run the format command before you push else the  build will fail
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Install surge
        run: npm install -g surge
      - name: Deploy to Surge
        if: github.event_name == 'push'
        run: surge --project ./build --domain obsolete-talk.surge.sh # remember when you run surge locally you have to provide with the project directory (build folder)  and get the URL for the domain
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
